/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as NoteIDRouteImport } from './routes/$noteID'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteIDRemoveRouteImport } from './routes/$noteID.remove'
import { Route as NoteIDEditRouteImport } from './routes/$noteID.edit'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIDRoute = NoteIDRouteImport.update({
  id: '/$noteID',
  path: '/$noteID',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIDRemoveRoute = NoteIDRemoveRouteImport.update({
  id: '/remove',
  path: '/remove',
  getParentRoute: () => NoteIDRoute,
} as any)
const NoteIDEditRoute = NoteIDEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => NoteIDRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$noteID': typeof NoteIDRouteWithChildren
  '/create': typeof CreateRoute
  '/$noteID/edit': typeof NoteIDEditRoute
  '/$noteID/remove': typeof NoteIDRemoveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$noteID': typeof NoteIDRouteWithChildren
  '/create': typeof CreateRoute
  '/$noteID/edit': typeof NoteIDEditRoute
  '/$noteID/remove': typeof NoteIDRemoveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$noteID': typeof NoteIDRouteWithChildren
  '/create': typeof CreateRoute
  '/$noteID/edit': typeof NoteIDEditRoute
  '/$noteID/remove': typeof NoteIDRemoveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$noteID' | '/create' | '/$noteID/edit' | '/$noteID/remove'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$noteID' | '/create' | '/$noteID/edit' | '/$noteID/remove'
  id:
    | '__root__'
    | '/'
    | '/$noteID'
    | '/create'
    | '/$noteID/edit'
    | '/$noteID/remove'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoteIDRoute: typeof NoteIDRouteWithChildren
  CreateRoute: typeof CreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$noteID': {
      id: '/$noteID'
      path: '/$noteID'
      fullPath: '/$noteID'
      preLoaderRoute: typeof NoteIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$noteID/remove': {
      id: '/$noteID/remove'
      path: '/remove'
      fullPath: '/$noteID/remove'
      preLoaderRoute: typeof NoteIDRemoveRouteImport
      parentRoute: typeof NoteIDRoute
    }
    '/$noteID/edit': {
      id: '/$noteID/edit'
      path: '/edit'
      fullPath: '/$noteID/edit'
      preLoaderRoute: typeof NoteIDEditRouteImport
      parentRoute: typeof NoteIDRoute
    }
  }
}

interface NoteIDRouteChildren {
  NoteIDEditRoute: typeof NoteIDEditRoute
  NoteIDRemoveRoute: typeof NoteIDRemoveRoute
}

const NoteIDRouteChildren: NoteIDRouteChildren = {
  NoteIDEditRoute: NoteIDEditRoute,
  NoteIDRemoveRoute: NoteIDRemoveRoute,
}

const NoteIDRouteWithChildren =
  NoteIDRoute._addFileChildren(NoteIDRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoteIDRoute: NoteIDRouteWithChildren,
  CreateRoute: CreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
